version: '3'
services:
  postgres:
    restart: on-failure
    image: postgres
    container_name: postgres1
    environment:
      POSTGRES_DB: lemon_bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1
    ports:
      - '5433:5432'
