spring:
  application:
    name: Lemon_Bank
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bankoflemons.ru:5433/lemon_bank_db
    username: postgres
    password: postgres1

  liquibase:
    enabled: true

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-access: ${ACCOUNT_SERVICE_JWT_EXPIRATION_ACCESS:604800}
server:
  port: 8080
